export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const REMOVE = 'REMOVE';
export const ADD_REVIEW = 'ADD REVIEW';
export const ADD_USER = 'ADD USER';
export const ADD_REVEIW_IN_RESTAURANT = 'ADD REVEIW IN RESTAURANT';
export const SET_ACTIVE_RESTAURANT = 'SET_ACTIVE_RESTAURANT';
